CREATE TABLE COMPANY_FROM_FILE(
  ID          	INTEGER PRIMARY KEY,
  NAME 	      	VARCHAR(100) ,
  ADDRES     	VARCHAR(200) ,
  CREATED_BY 	VARCHAR(100) ,
  CREATED_DATE   Date,
  UPDATE_BY 	VARCHAR(100) ,
  UPDATE_DATE   Date
);


CREATE TABLE CLIENT_FROM_FILE(
  ID          	INTEGER PRIMARY KEY,
  COMPANY_ID    INTEGER,
  NAME 	      	VARCHAR(100) ,
  EMAIL 	VARCHAR(100),
  PHONE 	VARCHAR(30),
  CREATED_BY 	VARCHAR(100) ,
  CREATED_DATE   Date,
  UPDATE_BY 	VARCHAR(100) ,
  UPDATE_DATE   Date
);